name: action_create test

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
        
jobs:
  test:
    runs-on: ubuntu:latest
    container:
      image: debian:11
    steps:
    - uses: actions/checkout@v3
    - uses: tnsdyd/action_create@master
