name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.KEY}}
      - name: c2
        run: ip a
