name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: |
          ssh -i /root/id_rsa.pem root@10.10.210.21
      - name: c2
        run: ip a
