name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: ls
      - name: SSH Command
  # You may pin to the exact commit or the version.
  # uses: D3rHase/ssh-command-action@981832f056c539720824429fa91df009db0ee9cd
        uses: D3rHase/ssh-command-action@v0.2.1
        with:
    # hostname / IP of the server
          HOST: 192.168.4.10
    # ssh port of the server
          PORT: 22
    # user of the server
          USER: root
    # private ssh key registered on the server
          PRIVATE_SSH_KEY: ${{ secrets.KEY }}
    # command to be executed
          COMMAND: echo Hello World!
      - name: c2
        run: ip a
