name: self-host test
on: 
  workflow_dispatch: 
    inputs: 
      logLevel:
        description: "Log level"
        required: true
        default: "waring"
        
  
jobs: 
  test:
    runs-on: self-hosted
    container: 
      image: 10.10.210.11:5000/test:1.0
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          java -version
          ls
