name: self-container test
on: 
  workflow_dispatch: 
    inputs: 
      logLevel:
        description: "Log level"
        required: true
        default: "waring"
        
  
jobs: 
  test:
    runs-on: self-hosted
    container: 
      image: alpine:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          ls
