name: test123
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          sh build.sh
  scp:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: test123
          path: /root/mvntest/test2/target/test2.war
      - uses: actions/download-artifact@v3
        with:
          name: test123
          path: /root/gittest
      - name: ssh-scp
        run: |
          sh test.sh
  deploy:
    runs-on: self-hosted
    needs: scp
    steps:
      - uses: actions/checkout@v3
      - name: deploy-ssh
        run: sh shell.sh
      - name: deploy.sh
        run: sh deploy.sh
    
