name: test123
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Update image on server
        run: |
          sh test.sh
